export const GET_DATA_LOADING = "GET_DATA_LOADING";
export const GET_DATA_SUCCESS = "GET_DATA_SUCCESS";
export const GET_DATA_ERROR = "GET_DATA_ERROR";

export const GET_SEARCH_DATA_SUCCESS = "GET_SEARCH_DATA_SUCCESS";
export const GET_SEARCH_DATA_ERROR = "GET_SEARCH_DATA_ERROR";
export const GET_SEARCH_DATA_LOOADING = "GET_SEARCH_DATA_LOOADING";
export const GET_SEARCH_DATA_REMOVED = "GET_SEARCH_DATA_REMOVED";

export const ADD_TO_CART_SUCCESS = "ADD_TO_CART_SUCCESS";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const ORDER_SUCCESS = "ORDER_SUCCESS";
